### ISSUE TITLE
Is it possible run server as standalone app (windows/linux) ?

### ISSUE THREAD

**Issue by ShockWave2048** [debox-dev/Teleport#3]
Hi! Is it possible run server as standalone app (windows/linux) ?
Or it's for Unity runtime only?
Thanks for answer!

**Comment by debox-dev** [comment]
Hi,
There are a few options here.

First of all, you can build it with Unity as a "Server build" (headless) for Linux and then it will be a stand alone server with all the unity features inside (colliders, etc..) but without graphics. You can choose "Server build" from the "Build settings" window in Unity.

If you don't want to use Unity at all, then you can use a pure C# server. Teleport will require some minor tweaks - but it shouldn't be a problem at all.
However, you will not have server-side features like physics, collisions, etc.. or you will have to get your own C# systems to simulate physics, and you wont have MonoBehaviours at all. There are features of Unity, not Teleport. In such a case, without Unity - Teleport is just the "Networking" layer.

In option 2 you don't have the functionality of the classes in the DeBox.Teleport.Unity namespace.
You will have to instantiate your own ```TeleportServerProcessor``` and ```TeleportClientProcessor```, but again - it should work.

**Comment by ShockWave2048** [comment]
Thanks debox-dev!
But Unity physics sim for each net room session, it's need run new instance for server?

**Comment by debox-dev** [comment]
That depends on your type of game.

Are you programming an mmo? 
If so you will need one server that is always 'alive'

Are you programming a moba? Rts? Fps? Something with a start and end? Then yes. This is similar to the original Unity networking system and any other network infrastructure provided by 3rd party companies.

You will either need to write your own infrastructure or you can use debox commercial products (we provide matchmaking, server instance management, servers, account management, leaderboards and more, depending on your needs) but these solutions are not open-source and cost money. We only open-source the base network layer. (Similar to Unity and other 3rd party network infra providers).
You can use Teleport with other companys' products that provide such services. You are not obligated to use our products at all when you use Teleport.

**Comment by ShockWave2048** [comment]
Ok, i understand!

**Comment by debox-dev** [comment]
In addition, are you writing a coop game? One of the players can be the server. 
Valves' Steam provides nice match making capabilities for such games for free if you use their platform

**Comment by debox-dev** [comment]
Thank you for taking the time to ask these questions. I have added a task to add these to the README

**Comment by ShockWave2048** [comment]
It's turn based game. No phys, standalone server. Own match making system.
