### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [debox-dev/Teleport#7]
HI @debox-dev,

Thanks for making the great upm package. I'm the creator of [OpenUPM](https://openupm.com/docs/#scope-registry-and-command-line-tool) platform, an open source UPM registry and continuous build service based on git tags. So far it is hosting more than 150+ UPM packages.

To make it happens, I would suggest you to make GitHub releases (which create git tags) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

Then you can submit your package here: https://openupm.com/packages/add/

**Comment by debox-dev** [comment]
Hi @favoyang 

Thank you for contacting me and bringing my attention to OpenUPM, a great initiative!

I immediately set up the release process and now Teleport will produce releases automagically.
The package was submitted via the link you provided.

I recommend you'll add the setup of the required NPM_TOKEN to your tutorial, as I had to investigate a bit until the CI configuration worked out.

Regards,
   Lital

**Comment by favoyang** [comment]
Thanks for the quick response. Well, the tutorial won't need a NPM_TOKEN, because in `.releaserc.json` the "@semantic-release/npm" step set "npmPublish" to false. And your setup seems a bit messy now.
- The recent two commit messages are "chore(release): x.y.z", without `[skip ci]` which defined in `.releaserc.json`. It looks like a manually commit, instead of a CI commit.
- The version 0.0.9 was tagged, but the version of package.json is 0.0.10
- The version 0.0.9 was tagged from a non-exist commit (9af4172) of master branch, this will caused the semantic-release (the tool behind the CI) to reset your version from 1.0.0.
- No CHANGELOG.md created.

Here's one way to fix it.

1. Delete current GitHub release. Go to https://github.com/favoyang/Teleport/releases/tag/v0.0.9, click delete
1. Recreate/retag a v0.0.9 GitHub release from your master branch, select 23b2e5a for example. This will give us a good existing git tag to analyze.
1. Delete the local tag 
    ```
    # delete old tag
    $ git tag -d v0.0.9
    
    # pull new tag
    $ git pull
    
    # verify
    $ git log -1
    commit 23b2e5aad16ea5cd8afb9e1b3f25bf89547f5a61 (HEAD -> master, tag: v0.0.9, 
    origin/master, origin/HEAD)
    ```
1. (optional) install semantic-release to verify setup with dry-run.
      - install semantic-release
        ```
        npm install -g semantic-release @semantic-release/changelog @semantic-release/git
        ```
      - request a [github token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)
      - dry-run, it should tell you no release will create based on the commit message analytics 
        ```
        GH_TOKEN=YOUR_TOKEN semantic-release --dry-run
        ```
1. (optional) Delete the NPM_TOKEN from the CI, create a new test commit with message "fix: remove NPM_TOKEN from CI"
1. (optional) dry-run again, it should tell you a new release 0.0.10 will be made (because last GitHub release was 0.0.9)
1. (optional) push to git server, wait the CI to release 0.0.10, and CHANGELOG.md will be created
1. (optional) `git pull --rebase` before your next commit.

BTW, I haven't see your PR for submitting this package. But Let's solve the CI thing first.

**Comment by debox-dev** [comment]
@favoyang 
Thanks for the instructions. I'm done fixing the branch.  Please note I rebased my master to a previous commit. So if you forked in the last 2-4 hours I recommend you'll replace your master.

Should I try and resubmit the PR?

**Comment by favoyang** [comment]
Yes, please.

**Comment by debox-dev** [comment]
Pull request created (manually, for some reason I couldn't follow up on the automated process from the website, the submit button was disabled and I couldn't see any reason why

**Comment by favoyang** [comment]
That's weird. A folk said it's a bug of GitHub, if you delete a few letter of a filename, then type them back, the button will be enabled. But I haven't get a chance to reproduce it.

Anyway, the package has been processed correctly. I also updated the [license field to MIT.](https://github.com/openupm/openupm/commit/865167dbc5889dc485f58787c4066ff018011302) 

https://openupm.com/packages/com.debox.teleport/
